export const GET_COMMENTS_FOR_COMMENT = 'DEEYE.GET_COMMENTS_FOR_COMMENT';
export const GET_COMMENTS_FOR_COMMENT_SUCCESS = 'DEEYE.GET_COMMENTS_FOR_COMMENT_SUCCESS';

export const CREATE_COMMENT_FOR_COMMENT = 'DEEYE.CREATE_COMMENT_FOR_COMMENT';
export const CREATE_COMMENT_FOR_COMMENT_SUCCESS = 'DEEYE.CREATE_COMMENT_FOR_COMMENT_SUCCESS';

export const CREATE_COMMENT_FOR_POST = 'DEEYE.CREATE_COMMENT_FOR_POST';

export const LIKE_COMMENT = 'DEEYE.LIKE_COMMENT';

export const UPDATE_COMMENT_SUCCESS = 'DEEYE.UPDATE_COMMENT_SUCCESS';
