export const GET_POSTS_LIST = 'DEEYE.GET_POSTS_LIST';
export const GET_POSTS_LIST_SUCCESS = 'DEEYE.GET_POSTS_LIST_SUCCESS';
export const GET_POSTS_LIST_FAIL = 'DEEYE.GET_POSTS_LIST_FAIL';

export const GET_POSTS_LIST_FOR_UNSIGNED = 'DEEYE.GET_POSTS_LIST_FOR_UNSIGNED';

export const CREATE_POST = 'DEEYE.CREATE_POST';
export const CREATE_POST_SUCCESS = 'DEEYE.CREATE_POST_SUCCESS';

export const UPLOAD_FILE = 'DEEYE.UPLOAD_FILE';

export const TOGGLE_POST_VISIBILITY = 'DEEYE.TOGGLE_POST_VISIBILITY';
export const TOGGLE_POST_VISIBILITY_SUCCESS = 'DEEYE.TOGGLE_POST_VISIBILITY_SUCCESS';

export const DELETE_POST = 'DEEYE.DELETE_POST';
export const DELETE_POST_SUCCESS = 'DEEYE.DELETE_POST_SUCCESS';

export const UPDATE_POST = 'DEEYE.UPDATE_POST';
export const UPDATE_POST_SUCCESS = 'DEEYE.UPDATE_POST_SUCCESS';

export const REPORT_POST = 'DEEYE.REPORT_POST';
export const SAVE_POST = 'DEEYE.SAVE_POST';
export const LIKE_POST = 'DEEYE.LIKE_POST';

export const SHARE_POST = 'DEEYE.SHARE_POST';
