export const GET_POSTS_LIST = 'DEEYE.GET_POSTS_LIST';
export const GET_POSTS_LIST_SUCCESS = 'DEEYE.GET_POSTS_LIST_SUCCESS';
export const GET_POSTS_LIST_FAIL = 'DEEYE.GET_POSTS_LIST_FAIL';
export const CREATE_POST = 'DEEYE.CREATE_POST';
export const CREATE_POST_SUCCESS = 'DEEYE.CREATE_POST_SUCCESS';
export const UPLOAD_FILE = 'DEEYE.UPLOAD_FILE';
export const TOGGLE_POST_VISIBILITY = 'DEEYE.TOGGLE_POST_VISIBILITY';
export const TOGGLE_POST_VISIBILITY_SUCCESS = 'DEEYE.TOGGLE_POST_VISIBILITY_SUCCESS';
