export const COMET_CHAT_LOGIN = 'DEEYE.COMET_CHAT_LOGIN';
export const COMET_CHAT_LOGIN_START = 'DEEYE.COMET_CHAT_LOGIN_START';
export const COMET_CHAT_LOGIN_SUCCESS = 'DEEYE.COMET_CHAT_LOGIN_SUCCESS';
export const COMET_CHAT_LOGIN_FAIL = 'DEEYE.COMET_CHAT_LOGIN_FAIL';
