export const ADD_BADGE_COUNT = 'DEEYE.ADD_BADGE_COUNT';
export const EMPTY_BADGE_COUNT = 'DEEYE.EMPTY_BADGE_COUNT';
export const GET_ALERT_LIST = 'DEEYE.GET_ALERT_LIST';
export const GET_ALERT_LIST_SUCCESS = 'DEEYE.GET_ALERT_LIST_SUCCESS';
export const GET_ALERT_LIST_FAIL = 'DEEYE.GET_ALERT_LIST_FAIL';
