export const BASE_URL = 'http://192.168.109.224:8000/api';
export const ASSET_BASE_URL = 'http://192.168.109.224:8000/storage/';

export const IMAGES_PATH = {
  gmail: require('src/assets/images/gmail.png'),
  instagram: require('src/assets/images/instagram.png'),
  facebook: require('src/assets/images/facebook.png'),
  yahoo: require('src/assets/images/yahoo.png'),
  email: require('src/assets/images/material-email.png'),
  phone: require('src/assets/images/material-phone-android.png'),
  checked: require('src/assets/images/feather-check-circle.png'),
  unchecked: require('src/assets/images/feather-check-circle-1.png'),
  onboardingGlobal: require('src/assets/images/Group-2431.png'),
  onboardingRealTime: require('src/assets/images/Group-2426.png'),
  onboardingProximity: require('src/assets/images/Group-2432.png'),
  onboardingExtendSearch: require('src/assets/images/Group-2433.png'),
  shapeActive3: require('src/assets/images/Shape-active-3.png'),
  photoSizeSelect1: require('src/assets/images/Icon-material-photo-size-select-actual-1.png'),
  featherVideo1: require('src/assets/images/Icon-feather-video-1.png'),
  setting: require('src/assets/images/Symbol-28–187.png'),
  comment: require('src/assets/images/Icon-feather-message-circle.png'),
  save: require('src/assets/images/Icon-feather-bookmark.png'),
  save1: require('src/assets/images/Icon-feather-bookmark-1.png'),
  support: require('src/assets/images/Icon-feather-heart.png'),
  support1: require('src/assets/images/Icon-feather-heart-1.png'),
  share: require('src/assets/images/Icon-ionic-md-share-alt.png'),
  send: require('src/assets/images/Icon-feather-send.png'),
  camera: require('src/assets/images/Icon-feather-camera-1.png'),
  fileUploadBlue: require('src/assets/images/Missing_Person/Blue_Icon-material-file-upload.png'),
  fileUploadRed: require('src/assets/images/Missing_Person/Icon-material-file-upload.png'),
  fileUploadGreen: require('src/assets/images/Missing_Person/Icon-material-file-upload-1.png'),
  featherCalendar: require('src/assets/images/Missing_Person/Icon-feather-calendar.png'),
  awesomeFemaleWhite: require('src/assets/images/Missing_Person/Icon-awesome-female.png'),
  awesomeFemalePrimary: require('src/assets/images/Missing_Person/Icon-awesome-female-1.png'),
  awesomeMaleWhite: require('src/assets/images/Missing_Person/Icon-awesome-male-1.png'),
  awesomeMalePrimary: require('src/assets/images/Missing_Person/Icon-awesome-male.png'),
}
