export const GET_USER_POSTS_LIST = 'DEEYE.GET_USER_POSTS_LIST';
export const GET_USER_INFO_COUNTER = 'DEEYE.GET_USER_INFO_COUNTER';
export const SET_USER_SUPPORT = 'DEEYE.SET_USER_SUPPORT';
export const SET_USER_NOTIFICATION = 'DEEYE.SET_USER_NOTIFICATION';
export const SET_USER_INFO_UPDATE = 'DEEYE.SET_USER_INFO_UPDATE';
