export const SET_FOLLOW = 'DEEYE.SET_FOLLOW';
export const GET_FOLLOW_LIST = 'DEEYE.GET_FOLLOW_LIST';
export const GET_FOLLOW_LIST_SUCCESS = 'DEEYE.GET_FOLLOW_LIST_SUCCESS';
export const GET_FOLLOW_LIST_FAIL = 'DEEYE.GET_FOLLOW_LIST_FAIL';
export const REMOVE_FOLLOW = 'DEEYE.REMOVE_FOLLOW';